[package]
name = "rvs_test"
version = "0.3.3"
authors = ["Abdulla Abdurakhmanov <me@abdolence.dev>"]
edition = "2021"
publish = false
license = "Apache-2.0"
description = "Tests for macros implementation for Value Classes in Rust"
repository = "https://github.com/abdolence/rust-value-struct"
keywords = ["value", "class"]

[dependencies]
rvstruct = { version = "0.3", path = "../rvs"}
